---

name: "Infra setup Production"

on:
  
 workflow_dispatch:
    
jobs:

  build: 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
      AWS_REGION: ${{ secrets.PROD_REGION }}

    steps: 

      - name: "Repository Chcekout"
        uses: actions/checkout@v3

      - name: "Terraform Installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: "Initializing Terraform"
        run: |
          terraform init \
            --backend-config="bucket=${{ secrets.PROD_S3_BUCKET }}" \
            --backend-config="key=terraform.tfstate" \
            --backend-config="access_key=${{ secrets.PROD_ACCESS_KEY }}" \
            --backend-config="secret_key=${{ secrets.PROD_SECRET_KEY }}" \
            --backend-config="region=${{ secrets.PROD_REGION }}" \


      - name: "Terraform destroy"
        run: |
          terraform destroy \
            -var "instance_type=${{ github.event.inputs.instance_type }}" \
            -var "instance_ami=${{ github.event.inputs.instance_ami }}" \
            -auto-approve        
